### ISSUE TITLE
Words with duplicate letters are yellow in the right spot

### ISSUE THREAD

**Issue by ajchili** [nickhudkins/wordle#9]
can you please fix this in post?

<img width="1904" alt="Screen Shot 2022-09-06 at 4 31 25 PM" src="https://user-images.githubusercontent.com/7911799/188732376-106d3019-2f47-49a2-b83b-434fad0947ec.png">

Please note, I have attached a screenshot from one of my best games.

**Comment by JoeHartzell** [comment]
+1 ruined my whole day

**Comment by nickhudkins** [comment]
Please add a failing test case as the algorithm is (almost) perfect, and I would hate to introduce regressions for my CUSTOMERS

**Comment by nickhudkins** [comment]
Dive Deep. Show me a sense of Ownership, maybe you could learn and be curious. I'm interested to see if this is an invalid but, but I will disagree but commit.

**Comment by ajchili** [comment]
I have Disagree and Commit here, I think you need to Strive to be the Worlds Best Employer and fix this for me.

**Comment by ajchili** [comment]
CAn I please request a DFD for the ECD?

**Comment by ajchili** [comment]
Another stellar game by yours truly which experiences the same horrid bug. I must also complain about the word list, according to my expert research ([source](https://www.wordhippo.com/what-is/starting-with/5-letter-words-para.html)) and extensive talk with my fellows, today's word was not bussin'.

<img width="1060" alt="Screen Shot 2022-09-08 at 3 22 26 PM" src="https://user-images.githubusercontent.com/7911799/189208431-422e9c53-d8f6-4121-9b06-ea963301643b.png">

**Comment by ajchili** [comment]
Alright, this is getting a little out of hand. My associates and I (Joe, Sam, and Andrew), all saw quite a sight today 😠


<img width="1904" alt="Screen Shot 2022-11-07 at 5 19 35 PM" src="https://user-images.githubusercontent.com/7911799/200428115-7219d31e-80a7-4d2b-9dc3-982bfb64ffb1.png">

<img width="1904" alt="Screen Shot 2022-11-07 at 5 21 22 PM" src="https://user-images.githubusercontent.com/7911799/200428133-83d32dd3-5a0d-41f3-8c4e-d374c4551125.png">


Within both images, again of excellent games, we see quite a not bussin' word being presented to the customer. Can we please rid this great application of this horrible bug.

**Comment by ajchili** [comment]
This is getting ridiculous. I once again have encountered this issue, this time within a week of the last one!

<img width="1015" alt="Screen Shot 2022-11-14 at 12 34 22 PM" src="https://user-images.githubusercontent.com/7911799/201728491-6e75d3f8-f7b2-4999-9623-379300896e5d.png">

**Comment by nickhudkins** [comment]
I believe this has been fixed here: https://github.com/nickhudkins/wordle/commit/05f3407ad1e8a9b8f7a67142cab2fa725991fb43
